---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://willeponken.me"
title: "willeponken"
subtitle: "William Wennerström"
canonifyurls: true
theme: "willeponken"

params:
  Subtitle: "William Wennerström"
...
